workflows:
  sample-workflow:
    name: EggCare workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: eggcare_apikey
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.appgroupsofchick.ChickCare
      vars:
        APP_STORE_CONNECT_KEY: eggcare_apikey
        APP_STORE_APPLE_ID: 6753303972
        BUNDLE_ID: "com.appgroupsofchick.ChickCare"
        XCODE_PROJECT: "ChickCare.xcodeproj"
        XCODE_SCHEME: "ChickCare"
    scripts:
      - name: Clean build folder
        script: |
          echo "Cleaning build artifacts..."
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf .build
          rm -rf build/
          xcodebuild clean -project "$CM_BUILD_DIR/$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
      - name: Resolve SPM Dependencies
        script: |
          echo "Resolving SPM dependencies..."
          xcodebuild -resolvePackageDependencies -project "$CM_BUILD_DIR/$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          #!/bin/sh
          cd $CM_BUILD_DIR
          echo "Current directory: $(pwd)"
          
          # Проверяем наличие Info.plist
          INFO_PLIST_PATH="ChickCare/Info.plist"
          if [ ! -f "$INFO_PLIST_PATH" ]; then
            echo "Error: Info.plist not found at $INFO_PLIST_PATH"
            find . -name Info.plist
            exit 1
          fi
          
          # Проверяем текущее значение
          echo "Before update:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$INFO_PLIST_PATH" || echo "No CFBundleVersion found"
          
          # Получаем последний билд из App Store Connect
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          NEW_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          echo "Latest build number: $LATEST_BUILD_NUMBER, Setting new: $NEW_BUILD_NUMBER"
          
          # Обновляем через agvtool
          agvtool new-version -all $NEW_BUILD_NUMBER
          
          # Принудительно обновляем Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" "$INFO_PLIST_PATH"
          
          # Проверяем после обновления
          echo "After update:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$INFO_PLIST_PATH"
          
          # Дополнительно проверяем Info.plist в финальной сборке
          cat "$INFO_PLIST_PATH"
      - name: Build ipa for distribution
        script: |
          echo "Building IPA..."
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --verbose \
            --additional-build-settings \
              COMPILER_INDEX_STORE_ENABLE=NO \
              SWIFT_TREAT_WARNINGS_AS_ERRORS=NO \
              CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        auth: integration
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: SCHEDULED
